# This YAML file describes your package. Stack will automatically generate a
# Cabal file when you run `stack build`. See the hpack website for help with
# this file: <https://github.com/sol/hpack>.
benchmarks:
  megaparsectest-benchmarks:
    dependencies:
    - base
    - megaparsectest
    - criterion
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    main: Main.hs
    source-dirs: benchmark
category: Other
description: megaparsectest is a new Haskeleton package.
executables:
  megaparsectest:
    dependencies:
    - base
    - megaparsectest
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    main: Main.hs
    source-dirs: executable
extra-source-files:
- CHANGELOG.md
- LICENSE.md
- package.yaml
- README.md
- stack.yaml
ghc-options: -Wall
github: githubuser/megaparsectest
library:
  dependencies:
  - base
  - megaparsec
  - raw-strings-qq
  source-dirs: library
license: MIT
maintainer: Author name here
name: megaparsectest
synopsis: A new Haskeleton package.
tests:
  megaparsectest-test-suite:
    dependencies:
    - base
    - megaparsectest
    - tasty
    - tasty-hspec
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    main: Main.hs
    source-dirs: test-suite
version: '0.0.0'
